### ISSUE TITLE
Containerization on ARM misses GLIBC_2.15

### ISSUE THREAD

**Issue by DoubleMalt** [cloudfleet/blimp-parachute#2]
Error message: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.15' not found (required by /opt/cloudfleet/apps/ccl/armcl

**Comment by easye** [comment]
@DoubleMalt  Can you share the diagnostic output of the platform that the init.bash centralized rc script from engineroom emits on the platform?  I am assuming RPi2 as the underlying hardware?

**Comment by DoubleMalt** [comment]
That builders are cuboxes.

**Comment by easye** [comment]
Can you set me up with an ssh key later today to one of them?

**Comment by DoubleMalt** [comment]
The missing thing is inside the docker container. Do you get a different
message on your RPi?

**Comment by DoubleMalt** [comment]
Builder arch info:

root@marina:~#     uname -a
Linux marina 3.14.14-cubox-i #2 SMP Wed Mar 11 13:01:02 CET 2015 armv7l
GNU/Linux

**Comment by easye** [comment]
Fixed  in https://github.com/cloudfleet/blimp-parachute/commit/f2c400b81124b38241b7143920135d3907d13d60
N.b. there is still a remaining issue in creating the arm32 container; see https://github.com/cloudfleet/blimp-parachute/issues/3
